#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Cache\Adapter\Redis\RedisCachePool;
use function Datashaman\Logic\repr;
use Dotenv\Dotenv;
use Github\Client;
use phpDocumentor\Reflection\DocBlockFactory;

$dotenv = Dotenv::create(getcwd());
$dotenv->load();

$options = getopt('o', ['gists']);

$client = new Redis();
$client->connect('127.0.0.1', 6379);

$pool = new RedisCachePool($client);

$client = new Client();
$client->addCache($pool);

$client->authenticate(getenv('GITHUB_TOKEN'), null, Client::AUTH_URL_TOKEN);

if (isset($options['gists'])) {
    $gists = $client->api('user')->gists('datashaman');
}

$parser = new Parsedown();

function markdown($text)
{
    global $parser;

    return $parser->text($text);
}

function getArguments($function, $docBlock = null)
{
    $tags = [];

    if ($docBlock) {
        $tags = array_reduce(
            $docBlock->getTagsByName('param'),
            function ($acc, $tag) {
                $name = $tag->getVariableName();

                $acc[$name] = [
                    'type' => (string) $tag->getType(),
                    'description' => preg_replace('#(^\<p>|\</p>$)#', '', markdown((string) $tag->getDescription())),
                ];

                return $acc;
            },
            []
        );
    }

    return array_map(
        function ($param) use ($tags) {
            $name = $param->getName();

            $arg = [
                'default' => null,
                'description' => isset($tags[$name]['description'])
                    ? $tags[$name]['description']
                    : null,
                'name' => $name,
                'type' => isset($tags[$name]['type'])
                    ? $tags[$name]['type']
                    : ($param->hasType() ? (string) $param->getType() : false),
                'variadic' => $param->isVariadic(),
            ];

            if ($param->isDefaultValueAvailable()) {
                if ($param->isDefaultValueConstant()) {
                    $arg['default'] = $param->getDefaultValueConstantName();
                } else {
                    $arg['default'] = repr($param->getDefaultValue());
                }
            }

            return $arg;
        },
        $function->getParameters()
    );
}

function getDocBlock($function)
{
    $factory = DocBlockFactory::createInstance();
    $docComment = $function->getDocComment();

    return $docComment
        ? $factory->create($docComment)
        : null;
}

function getDescription($docBlock)
{
    return markdown(preg_replace('#\s*<pre>.*</pre>\s*#s', '', (string) $docBlock->getDescription()));
}

function getSummary($docBlock)
{
    return markdown($docBlock->getSummary());
}

function getExample($docBlock)
{
    $description = (string) $docBlock->getDescription();

    if (preg_match('#<pre>\s*(.*)\s*</pre>#s', $description, $match)) {
        return str_replace('\\/', '/', $match[1]);
    }
}

function getReturn($docBlock)
{
    $tags = $docBlock->getTagsByName('return');

    if (!$tags) {
        return null;
    }

    $tag = $tags[0];

    return [
        'type' => (string) $tag->getType(),
        'description' => markdown((string) $tag->getDescription()),
    ];
}

function getHeader($function, $arguments)
{
    $arguments = array_map(
        function ($arg) {
            $str = '';

            if ($arg['type'] && strpos($arg['type'], '|') === false) {
                $str .= $arg['type'] . ' ';
            }

            if ($arg['variadic']) {
                $str .= '...';
            }

            $str .= '$' . $arg['name'];

            if ($arg['default']) {
                $str .= ' = ' . $arg['default'];
            }

            return $str;
        },
        $arguments
    );

    return $function->getShortName() . '(' . implode(', ', $arguments) . ')';
}

$classes = get_declared_classes();

function transformMethod($method)
{
    return [
        'name' => $method->getName(),
        'modifiers' => [
            'abstract' => $method->isAbstract(),
            'final' => $method->isFinal(),
            'generator' => $method->isGenerator(),
            'private' => $method->isPrivate(),
            'protected' => $method->isProtected(),
            'public' => $method->isPublic(),
            'static' => $method->isStatic(),
            'variadic' => $method->isVariadic(),
        ],
        'parameters' => array_map(
            function ($param) {
                $class = $param->getClass();

                return [
                    'class' => $class ? $class->getName() : null,
                    'defaultValue' => $param->isDefaultValueAvailable() ? $param->getDefaultValue() : null,
                    'defaultValueConstantName' => $param->isDefaultValueAvailable() && $param->isDefaultValueConstant() ? $param->getDefaultValueConstantName() : null,
                    'name' => $param->getName(),
                    'position' => $param->getPosition(),
                    'type' => (string) $param->getType(),
                    'modifiers' => [
                        'array' => $param->isArray(),
                        'callable' => $param->isCallable(),
                        'defaultValueAvailable' => $param->isDefaultValueAvailable(),
                        'defaultValueConstant' => $param->isDefaultValueAvailable() && $param->isDefaultValueConstant(),
                        'optional' => $param->isOptional(),
                        'passedByReference' => $param->isPassedByReference(),
                        'variadic' => $param->isVariadic(),
                    ],
                ];
            },
            $method->getParameters()
        ),
        'returnType' => $method->getReturnType(),
    ];
}

$classes = array_filter(
    array_map(
        function ($name) {
            $class = new ReflectionClass($name);

            $docBlock = getDocBlock($class);
            if ($docBlock && $docBlock->getTagsByName('nodocs')) {
                return;
            }

            $result = [
                'constants' => $class->getConstants(),
                'constructor' => transformMethod($class->getConstructor()),
                'file' => basename($class->getFilename(), '.php'),
                'interfaces' => $class->getInterfaceNames(),
                'methods' => [],
                'modifiers' => [
                    'abstract' => $class->isAbstract(),
                    'final' => $class->isFinal(),
                    'interface' => $class->isInterface(),
                    'trait' => $class->isTrait(),
                ],
                'name' => $name,
                'properties' => [],
                'shortName' => $class->getShortName(),
            ];

            foreach ($class->getProperties() as $property) {
                $result['properties'][$property->getName()] = [
                    'name' => $property->getName(),
                    'modifiers' => [
                        'private' => $property->isPrivate(),
                        'protected' => $property->isProtected(),
                        'public' => $property->isPublic(),
                        'static' => $property->isStatic(),
                    ],
                ];
            }

            foreach ($class->getMethods() as $method) {
                $result['methods'][$method->getName()] = transformMethod($method);
            }

            return $result;
        },
        array_filter(
            $classes,
            function ($class) {
                return preg_match('#^Datashaman\\\\Logic#', $class);
            }
        )
    )
);

usort($classes, function ($a, $b) {
    return $a['shortName'] <=> $b['shortName'];
});

if (isset($options['gists'])) {
    $indexedGists = [];

    foreach ($gists as $gist) {
        if (preg_match('#^(Datashaman\\\\Logic\\\\.+) Example$#', $gist['description'], $match)) {
            $indexedGists[$match[1]] = $gist;
        }
    }

    foreach ($classes as &$class) {
        if (isset($class['example'])) {
            $code = <<<CODE
<?php
<<<CONFIG
packages:
    - "datashaman/logic: dev-master"
CONFIG;
#
# This is a Melody script. http://melody.sensiolabs.org/
#

{$class['example']}
CODE;

            $description = $class['name'] . ' Example';

            $params = [
                'description' => $description,
                'files' => [
                    $description => [
                        'content' => $code,
                    ],
                ],
                'public' => true,
            ];

            if (isset($indexedGists[$class['name']])) {
                $gist = $indexedGists[$class['name']];
                $contents = file_get_contents($gist['files'][$description]['raw_url']);

                if ($contents !== $code) {
                    $gist = $client->api('gists')->update($gist['id'], $params);
                }
            } else {
                $gist = $client->api('gists')->create($params);
            }

            $class['gist'] = $gist['html_url'];
        }
    }
}

$classes = array_reduce(
    $classes,
    function ($acc, $class) {
        if (!isset($acc[$class['file']])) {
            $acc[$class['file']] = [];
        }

        $acc[$class['file']][] = $class;

        return $acc;
    },
    []
);

$json = json_encode($classes, JSON_PRETTY_PRINT);

if (isset($options['o'])) {
    file_put_contents($options['o'], $json);
} else {
    echo $json . PHP_EOL;
}
